spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/data/jpashop;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

# 운영환경에서 로그는 System.out이 아닌 로그를 통해서 찍어야함.
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace


